
package gov.utah.dts.alm.webservice.model;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "LogDataService", targetNamespace = "http://dts.utah.gov/alm/webservice/model", wsdlLocation = "http://applog.at.utah.gov:8080/ApplicationLogging/services/log.wsdl")
public class LogDataService
    extends Service
{

    private final static URL LOGDATASERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://applog.at.utah.gov:8080/ApplicationLogging/services/log.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        LOGDATASERVICE_WSDL_LOCATION = url;
    }

    public LogDataService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LogDataService() {
        super(LOGDATASERVICE_WSDL_LOCATION, new QName("http://dts.utah.gov/alm/webservice/model", "LogDataService"));
    }

    /**
     * 
     * @return
     *     returns LogData
     */
    @WebEndpoint(name = "LogDataSoap11")
    public LogData getLogDataSoap11() {
        return (LogData)super.getPort(new QName("http://dts.utah.gov/alm/webservice/model", "LogDataSoap11"), LogData.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LogData
     */
    @WebEndpoint(name = "LogDataSoap11")
    public LogData getLogDataSoap11(WebServiceFeature... features) {
        return (LogData)super.getPort(new QName("http://dts.utah.gov/alm/webservice/model", "LogDataSoap11"), LogData.class, features);
    }

}
