
package gov.utah.dts.alm.webservice.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "LogData", targetNamespace = "http://dts.utah.gov/alm/webservice/model")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LogData {


    /**
     * 
     * @param writeLogRequest
     * @return
     *     returns gov.utah.dts.alm.webservice.model.WriteLogResponse
     */
    @WebMethod(operationName = "WriteLog")
    @WebResult(name = "WriteLogResponse", targetNamespace = "http://dts.utah.gov/alm/webservice/model", partName = "WriteLogResponse")
    public WriteLogResponse writeLog(
        @WebParam(name = "WriteLogRequest", targetNamespace = "http://dts.utah.gov/alm/webservice/model", partName = "WriteLogRequest")
        WriteLogRequest writeLogRequest);

    /**
     * 
     * @param readLogRequest
     * @return
     *     returns gov.utah.dts.alm.webservice.model.ReadLogResponse
     */
    @WebMethod(operationName = "ReadLog")
    @WebResult(name = "ReadLogResponse", targetNamespace = "http://dts.utah.gov/alm/webservice/model", partName = "ReadLogResponse")
    public ReadLogResponse readLog(
        @WebParam(name = "ReadLogRequest", targetNamespace = "http://dts.utah.gov/alm/webservice/model", partName = "ReadLogRequest")
        ReadLogRequest readLogRequest);

}
